[window]
dimensions = { columns = 80, lines = 30 }
padding = { x = 4, y = 2 }
dynamic_padding = true
opacity = 0.9 
title = "Alacritty"
decorations="Full"

[font]
normal = { family = "Source Code Pro", style = "Regular" }
bold = { family = "Source Code Pro", style = "Bold" }
italic = { family = "Source Code Pro", style = "Italic" }
size = 12.0

[cursor]
style = { shape = "Block", blinking = "On" }

[terminal]
osc52 = "CopyPaste"
